### ISSUE TITLE
Tensor mis-match RuntimeError when use accelerate for gpt2-sentiment.py

### ISSUE THREAD

**Issue by oroojlooy** [lvwerra/trl#316]
I tried to run `gpt2-sentiment.py` by `accelerate` through `FSDP`. My accelerate yaml config is:
```
compute_environment: LOCAL_MACHINE
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: GPT2Block
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

With the latest TRL code I was getting the following error:
`The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, s o you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.` 
which based on `https://github.com/huggingface/accelerate/issues/570` and `https://github.com/pytorch/pytorch/issues/82461` I added the following piece of code to the `ppo_trainer.py` under the `else` block of `if is_deepspeed_used` condition:
```
  from accelerate.utils import DistributedType
  if self.accelerator.distributed_type == DistributedType.FSDP:
      rank = torch.distributed.get_rank()
      if rank == 0:
          text_in = "The purpose of life is "
      else:
          text_in = "Are you human? "
      query_tensors = self.tokenizer(text_in, return_tensors="pt").to(self.accelerator.device)["input_ids"]
      outputs = self.model(query_tensors)
```
This helps fixing the above issue, but results into the following error:
`RuntimeError: The size of tensor a (9846529) must match the size of tensor b (39386113) at non-singleton dimension 0`

Here is the corresponding call stack:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/20797260/234063353-f0ca4957-5fb9-404d-8bc0-ddd18bcd15f3.png">

I appreciate any help/comment.
