### ISSUE TITLE
Interest with pre-commit? 

### ISSUE THREAD

**Issue by vwxyzjn** [lvwerra/trl#408]
Hey, would you be interested in using pre-commit to do the formatting stuff? It can help take out some dependencies from `setup.py` and offer IMO a smoother experience (the CI checks nicely, and you can easily run to modify content in place). 

We can also add 

```
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: 
          - --py37-plus
```
which upgrade syntax and

```
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - -r
          - --exclude=wandb
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
```

which automatically removes unused variables and imports.
